version: 2
jobs:
  build:
    working_directory: ~/app

    docker:
      - image: circleci/openjdk:8-jdk-stretch

    steps:
      - checkout

      - restore_cache:
          key: app-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: app-{{ checksum "pom.xml" }}

      - run: |
          mvn package

          mkdir jar
          cp target/*.jar jar

      - store_test_results:
          path: target/surefire-reports

      - store_artifacts:
          path: jar

workflows:
  version: 2
  workflow:
    jobs:
    - build